server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3366/finalwork?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456