name: Checkstyle

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkstyle
        uses: daniel-andrews/checkstyle-action@v1.2.1
        with:
          config: ./config/checkstyle.xml
          path: ./src/
          reportType: files