name: Code Format Check

on:
  push:
    branches:
        - master
        - develop
  pull_request:
    branches:
        - master
        - develop
jobs:
  code-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Code format check
        run: npm run lint

      - name: Check format result
        run: |
          if [[ ${{ steps.code-format-check.outputs.exit-code }} -eq 0 ]]; then
            echo "Code format check passed."
          else
            echo "Code format check failed. Please fix the code format issues and try again."
            exit 1
          fi
