name: Code Quality Check

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          server-id: alimaven
          java-version: 11

      - name: Install dependencies and check code formatting
        run: |
          ./gradlew ktlintCheck

      - name: Run tests
        run: |
          ./gradlew test