name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout source code
      - uses: actions/checkout@v2
      # Cache maven .m2 directory
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Install Java 1.8
      - uses: actions/setup-java@v1
        with:
          server-id: alimaven
          java-version: 11
      # Code review with Checkstyle
      - name: Checkstyle
          run: |
            mvn checkstyle:checkstyle || true
            checkstyle_report_path=$(find target/site -name "checkstyle-result.xml")
            if [ -f "$checkstyle_report_path" ]; then
              echo "Checkstyle report: $checkstyle_report_path"
              echo "::error :: Checkstyle found issues in your code. Please fix them before continuing."
              exit 1
            fi
      # Code testing with JUnit
      - name: JUnit
        run: |
          mvn test
          test_report_path=$(find target/surefire-reports -name "TEST-*.xml")
          if [ -f "$test_report_path" ]; then
            echo "Test report: $test_report_path"
            junit_report=$(cat "$test_report_path")
            echo "::set-output name=junit_report::$junit_report"
          fi
      # Publish to Apache Maven Central
      #- run: mvn install:install-file "-Dfile=cobra.jar" "-DgroupId=com.cobra" "-DartifactId=cobra" "-Dversion=0.98.4" "-Dpackaging=jar" "-DgeneratePom=true"
      #- run: mvn clean compile
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging