name: Code Quality Check

on:
  push:
    branches:
      - master
      - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Setup Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Code Format Check with Checkstyle
      - name: Checkstyle
        run: |
          mvn checkstyle:checkstyle
          checkstyle_report_path=$(find target/site -name "checkstyle-result.xml")
          if [ -f "$checkstyle_report_path" ]; then
            echo "Checkstyle report: $checkstyle_report_path"
            echo "::error :: Checkstyle found issues in your code. Please fix them before continuing."
            exit 1
          fi

      # Unit Test with JUnit
      - name: JUnit Test
        run: |
          mvn test
          test_report_path=$(find target/surefire-reports -name "TEST-*.xml")
          if [ -f "$test_report_path" ]; then
            echo "Test report: $test_report_path"
            junit_report=$(cat "$test_report_path")
            echo "::set-output name=junit_report::$junit_report"
          else
            echo "::error ::No test report found. Please fix the failed test(s) before continuing."
            exit 1
          fi